name: Commitlint
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: |
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Link dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint commits
        run: yarn commitlint --from "origin/${BASE_REF}" --to "${GITHUB_SHA}"
        env:
          BASE_REF: ${{ github.base_ref }}
