name: 'Reviewer lottery'
on:
  pull_request:
    types:
      - opened
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  reviewer-lottery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config: '.github/reviewers-config.yml'
